"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";

type Stage = "idle" | "joining" | "recording" | "transcribing" | "done";

const API_BASE = process.env.NEXT_PUBLIC_LOCAL_API_BASE || "http://127.0.0.1:8000";

const SAMPLE_TRANSCRIPT = `MEETING TRANSCRIPT (simulated demo)
Generated by the Google Meet Bot prototype

[00:00] Host: Thanks everyone for joining, let's get started.
[00:04] Participant: Sounds good, I have the roadmap doc pulled up.
[00:11] Host: Great — first item, the Q3 rollout timeline.
[00:19] Participant: We're on track, just waiting on the design review.
[00:27] Host: Perfect, let's sync again once that lands.

This transcript is a placeholder — real sessions run locally through
OpenAI Whisper or AssemblyAI on the actual meeting audio.`;

const STEPS: { key: Stage; label: string }[] = [
  { key: "joining", label: "Joining meeting" },
  { key: "recording", label: "Recording audio + video" },
  { key: "transcribing", label: "Transcribing with Whisper" },
  { key: "done", label: "Transcript ready" },
];

type LiveResult = {
  transcript: string;
  audio_file: string | null;
  video_file: string | null;
  text_file: string | null;
  pdf_file: string | null;
};

type LiveStatus = {
  stage: Stage;
  error: string | null;
  session_id: string | null;
  result: LiveResult | null;
};

function stepState(stage: Stage, key: Stage) {
  const order: Stage[] = ["idle", "joining", "recording", "transcribing", "done"];
  const current = order.indexOf(stage);
  const target = order.indexOf(key);
  if (current > target) return "done";
  if (current === target) return "active";
  return "pending";
}

function Waveform() {
  const bars = new Array(28).fill(0);
  return (
    <div className="flex h-16 items-center gap-1">
      {bars.map((_, i) => (
        <motion.span
          key={i}
          className="w-1.5 rounded-full bg-gradient-to-t from-accent-a to-accent-b"
          animate={{ height: [6, 28, 10, 34, 8][i % 5] }}
          transition={{
            duration: 0.6 + (i % 4) * 0.1,
            repeat: Infinity,
            repeatType: "mirror",
            delay: i * 0.03,
          }}
        />
      ))}
    </div>
  );
}

async function fetchWithTimeout(url: string, options: RequestInit = {}, timeoutMs = 1500) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...options, signal: controller.signal });
  } finally {
    clearTimeout(timeout);
  }
}

export default function Prototype() {
  const [liveAvailable, setLiveAvailable] = useState<boolean | null>(null);
  const [stage, setStage] = useState<Stage>("idle");
  const [url, setUrl] = useState("");
  const [elapsed, setElapsed] = useState(0);
  const [error, setError] = useState<string | null>(null);
  const [liveResult, setLiveResult] = useState<LiveResult | null>(null);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);
  const pollRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    fetchWithTimeout(`${API_BASE}/api/status`)
      .then((res) => (res.ok ? setLiveAvailable(true) : setLiveAvailable(false)))
      .catch(() => setLiveAvailable(false));
  }, []);

  useEffect(() => {
    if (stage === "recording") {
      timerRef.current = setInterval(() => setElapsed((s) => s + 1), 1000);
    } else if (timerRef.current) {
      clearInterval(timerRef.current);
    }
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [stage]);

  const stopPolling = () => {
    if (pollRef.current) {
      clearInterval(pollRef.current);
      pollRef.current = null;
    }
  };

  const pollStatus = () => {
    stopPolling();
    pollRef.current = setInterval(async () => {
      try {
        const res = await fetchWithTimeout(`${API_BASE}/api/status`, {}, 3000);
        const data: LiveStatus = await res.json();
        setStage(data.stage);
        if (data.error) setError(data.error);
        if (data.result) setLiveResult(data.result);
        if (data.stage === "idle" || data.stage === "done") stopPolling();
      } catch {
        // transient network hiccup while polling; keep trying
      }
    }, 1200);
  };

  const join = async () => {
    if (liveAvailable) {
      setError(null);
      setStage("joining");
      try {
        const res = await fetchWithTimeout(
          `${API_BASE}/api/join`,
          {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify({ meeting_url: url }),
          },
          5000
        );
        if (!res.ok) {
          const body = await res.json().catch(() => ({}));
          setError(body.detail || "Failed to start join");
          setStage("idle");
          return;
        }
        pollStatus();
      } catch {
        setError("Could not reach the local bot server");
        setStage("idle");
      }
      return;
    }

    setStage("joining");
    setTimeout(() => setStage("recording"), 1600);
  };

  const stop = async () => {
    if (liveAvailable) {
      setStage("transcribing");
      try {
        await fetchWithTimeout(`${API_BASE}/api/stop`, { method: "POST" }, 5000);
        pollStatus();
      } catch {
        setError("Could not reach the local bot server");
      }
      return;
    }

    setStage("transcribing");
    setTimeout(() => setStage("done"), 1800);
  };

  const reset = () => {
    stopPolling();
    if (liveAvailable) {
      fetchWithTimeout(`${API_BASE}/api/reset`, { method: "POST" }, 3000).catch(() => {});
    }
    setStage("idle");
    setElapsed(0);
    setUrl("");
    setError(null);
    setLiveResult(null);
  };

  const download = () => {
    const blob = new Blob([SAMPLE_TRANSCRIPT], { type: "text/plain" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "meet-bot-demo-transcript.txt";
    link.click();
    URL.revokeObjectURL(link.href);
  };

  const minutes = String(Math.floor(elapsed / 60)).padStart(2, "0");
  const seconds = String(elapsed % 60).padStart(2, "0");

  return (
    <section id="prototype" className="relative mx-auto max-w-4xl px-6 py-24">
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-80px" }}
        transition={{ duration: 0.6 }}
        className="mb-10 text-center"
      >
        <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">
          Try the workflow
        </h2>
        <p className="mx-auto mt-3 max-w-xl text-muted">
          {liveAvailable
            ? "Your local bot server is running — this panel controls it for real: it will open Chrome, join the meeting below, and record your microphone and screen."
            : "This is a live, in-browser simulation so you can see the experience before installing anything. Run the bot's local API server on your own machine to control it for real from this page."}
        </p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-60px" }}
        transition={{ duration: 0.6, delay: 0.1 }}
        className="card-surface rounded-2xl p-6 sm:p-8"
      >
        <div className="mb-6 flex flex-wrap items-center gap-3">
          {STEPS.map((step) => {
            const state = stepState(stage, step.key);
            return (
              <div
                key={step.key}
                className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs transition ${
                  state === "active"
                    ? "border-accent-a/60 bg-accent-a/10 text-foreground"
                    : state === "done"
                      ? "border-border text-muted"
                      : "border-border/60 text-muted/50"
                }`}
              >
                <span
                  className={`h-1.5 w-1.5 rounded-full ${
                    state === "active"
                      ? "animate-pulse bg-accent-b"
                      : state === "done"
                        ? "bg-emerald-400"
                        : "bg-border"
                  }`}
                />
                {step.label}
              </div>
            );
          })}

          <div className="ml-auto flex items-center gap-1.5 text-xs text-muted">
            <span
              className={`h-1.5 w-1.5 rounded-full ${
                liveAvailable ? "bg-emerald-400" : liveAvailable === false ? "bg-border" : "animate-pulse bg-border"
              }`}
            />
            {liveAvailable === null ? "Checking for local bot…" : liveAvailable ? "Live mode" : "Demo mode"}
          </div>
        </div>

        {liveAvailable && stage === "idle" && (
          <div className="mb-4 rounded-lg border border-amber-500/30 bg-amber-500/10 px-3 py-2 text-xs text-amber-200">
            This will really join the meeting below and record audio + screen. Make sure you have the right to record everyone on the call.
          </div>
        )}

        {error && (
          <div className="mb-4 rounded-lg border border-red-500/30 bg-red-500/10 px-3 py-2 text-xs text-red-200">
            {error}
          </div>
        )}

        <AnimatePresence mode="wait">
          {stage === "idle" && (
            <motion.div
              key="idle"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col gap-4 sm:flex-row"
            >
              <input
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="https://meet.google.com/abc-defg-hij"
                className="flex-1 rounded-lg border border-border bg-background px-4 py-3 text-sm outline-none focus:border-accent-a"
              />
              <button
                onClick={join}
                disabled={liveAvailable === true && url.trim().length === 0}
                className="rounded-lg bg-foreground px-5 py-3 text-sm font-medium text-background transition hover:opacity-90 disabled:opacity-40"
              >
                Join Meeting
              </button>
            </motion.div>
          )}

          {stage === "joining" && (
            <motion.div
              key="joining"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center gap-3 py-4 text-sm text-muted"
            >
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-accent-a border-t-transparent" />
              Opening Chrome and joining {url || "the meeting"}…
            </motion.div>
          )}

          {stage === "recording" && (
            <motion.div
              key="recording"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col items-center gap-4 py-2"
            >
              <div className="flex items-center gap-2 text-sm text-muted">
                <span className="h-2 w-2 animate-pulse rounded-full bg-red-500" />
                Recording · {minutes}:{seconds}
              </div>
              <Waveform />
              <button
                onClick={stop}
                className="rounded-lg border border-border px-5 py-2.5 text-sm font-medium transition hover:bg-background"
              >
                Stop & Transcribe
              </button>
            </motion.div>
          )}

          {stage === "transcribing" && (
            <motion.div
              key="transcribing"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center gap-3 py-4 text-sm text-muted"
            >
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-accent-b border-t-transparent" />
              Running Whisper over the recording…
            </motion.div>
          )}

          {stage === "done" && (
            <motion.div
              key="done"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="flex flex-col gap-4"
            >
              <pre className="max-h-56 overflow-y-auto whitespace-pre-wrap rounded-lg border border-border bg-background p-4 text-xs leading-relaxed text-muted">
                {liveAvailable && liveResult ? liveResult.transcript : SAMPLE_TRANSCRIPT}
              </pre>
              <div className="flex flex-wrap gap-3">
                {liveAvailable && liveResult ? (
                  <>
                    {liveResult.text_file && (
                      <a
                        href={`${API_BASE}/api/download/text/${liveResult.text_file}`}
                        className="rounded-lg bg-foreground px-4 py-2.5 text-sm font-medium text-background transition hover:opacity-90"
                      >
                        Download Text
                      </a>
                    )}
                    {liveResult.pdf_file && (
                      <a
                        href={`${API_BASE}/api/download/pdf/${liveResult.pdf_file}`}
                        className="rounded-lg border border-border px-4 py-2.5 text-sm font-medium transition hover:bg-background"
                      >
                        Download PDF
                      </a>
                    )}
                    {liveResult.video_file && (
                      <a
                        href={`${API_BASE}/api/download/video/${liveResult.video_file}`}
                        className="rounded-lg border border-border px-4 py-2.5 text-sm font-medium transition hover:bg-background"
                      >
                        Download Video
                      </a>
                    )}
                  </>
                ) : (
                  <button
                    onClick={download}
                    className="rounded-lg bg-foreground px-4 py-2.5 text-sm font-medium text-background transition hover:opacity-90"
                  >
                    Download Sample Transcript
                  </button>
                )}
                <button
                  onClick={reset}
                  className="rounded-lg border border-border px-4 py-2.5 text-sm font-medium transition hover:bg-background"
                >
                  Run Again
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </section>
  );
}
