"use client";

import { useEffect, useRef, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";

type Stage = "idle" | "joining" | "recording" | "transcribing" | "done";

const SAMPLE_TRANSCRIPT = `MEETING TRANSCRIPT (simulated demo)
Generated by the Google Meet Bot prototype

[00:00] Host: Thanks everyone for joining, let's get started.
[00:04] Participant: Sounds good, I have the roadmap doc pulled up.
[00:11] Host: Great — first item, the Q3 rollout timeline.
[00:19] Participant: We're on track, just waiting on the design review.
[00:27] Host: Perfect, let's sync again once that lands.

This transcript is a placeholder — real sessions run locally through
OpenAI Whisper or AssemblyAI on the actual meeting audio.`;

const STEPS: { key: Stage; label: string }[] = [
  { key: "joining", label: "Joining meeting" },
  { key: "recording", label: "Recording audio + video" },
  { key: "transcribing", label: "Transcribing with Whisper" },
  { key: "done", label: "Transcript ready" },
];

function stepState(stage: Stage, key: Stage) {
  const order: Stage[] = ["idle", "joining", "recording", "transcribing", "done"];
  const current = order.indexOf(stage);
  const target = order.indexOf(key);
  if (current > target) return "done";
  if (current === target) return "active";
  return "pending";
}

function Waveform() {
  const bars = new Array(28).fill(0);
  return (
    <div className="flex h-16 items-center gap-1">
      {bars.map((_, i) => (
        <motion.span
          key={i}
          className="w-1.5 rounded-full bg-gradient-to-t from-accent-a to-accent-b"
          animate={{ height: [6, 28, 10, 34, 8][i % 5] }}
          transition={{
            duration: 0.6 + (i % 4) * 0.1,
            repeat: Infinity,
            repeatType: "mirror",
            delay: i * 0.03,
          }}
        />
      ))}
    </div>
  );
}

export default function Prototype() {
  const [stage, setStage] = useState<Stage>("idle");
  const [url, setUrl] = useState("");
  const [elapsed, setElapsed] = useState(0);
  const timerRef = useRef<ReturnType<typeof setInterval> | null>(null);

  useEffect(() => {
    if (stage === "recording") {
      timerRef.current = setInterval(() => setElapsed((s) => s + 1), 1000);
    } else if (timerRef.current) {
      clearInterval(timerRef.current);
    }
    return () => {
      if (timerRef.current) clearInterval(timerRef.current);
    };
  }, [stage]);

  const join = () => {
    setStage("joining");
    setTimeout(() => setStage("recording"), 1600);
  };

  const stop = () => {
    setStage("transcribing");
    setTimeout(() => setStage("done"), 1800);
  };

  const reset = () => {
    setStage("idle");
    setElapsed(0);
    setUrl("");
  };

  const download = () => {
    const blob = new Blob([SAMPLE_TRANSCRIPT], { type: "text/plain" });
    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = "meet-bot-demo-transcript.txt";
    link.click();
    URL.revokeObjectURL(link.href);
  };

  const minutes = String(Math.floor(elapsed / 60)).padStart(2, "0");
  const seconds = String(elapsed % 60).padStart(2, "0");

  return (
    <section id="prototype" className="relative mx-auto max-w-4xl px-6 py-24">
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-80px" }}
        transition={{ duration: 0.6 }}
        className="mb-10 text-center"
      >
        <h2 className="text-3xl font-semibold tracking-tight sm:text-4xl">
          Try the workflow
        </h2>
        <p className="mx-auto mt-3 max-w-xl text-muted">
          This is a live, in-browser simulation of the bot&apos;s workflow so you can see
          the experience before installing anything. The real bot runs locally — joining a
          real Chrome browser and recording your actual microphone and screen — which a
          hosted site like this can&apos;t do on your behalf.
        </p>
      </motion.div>

      <motion.div
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-60px" }}
        transition={{ duration: 0.6, delay: 0.1 }}
        className="card-surface rounded-2xl p-6 sm:p-8"
      >
        <div className="mb-6 flex flex-wrap gap-3">
          {STEPS.map((step) => {
            const state = stepState(stage, step.key);
            return (
              <div
                key={step.key}
                className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs transition ${
                  state === "active"
                    ? "border-accent-a/60 bg-accent-a/10 text-foreground"
                    : state === "done"
                      ? "border-border text-muted"
                      : "border-border/60 text-muted/50"
                }`}
              >
                <span
                  className={`h-1.5 w-1.5 rounded-full ${
                    state === "active"
                      ? "animate-pulse bg-accent-b"
                      : state === "done"
                        ? "bg-emerald-400"
                        : "bg-border"
                  }`}
                />
                {step.label}
              </div>
            );
          })}
        </div>

        <AnimatePresence mode="wait">
          {stage === "idle" && (
            <motion.div
              key="idle"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col gap-4 sm:flex-row"
            >
              <input
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="https://meet.google.com/abc-defg-hij"
                className="flex-1 rounded-lg border border-border bg-background px-4 py-3 text-sm outline-none focus:border-accent-a"
              />
              <button
                onClick={join}
                className="rounded-lg bg-foreground px-5 py-3 text-sm font-medium text-background transition hover:opacity-90"
              >
                Join Meeting
              </button>
            </motion.div>
          )}

          {stage === "joining" && (
            <motion.div
              key="joining"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center gap-3 py-4 text-sm text-muted"
            >
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-accent-a border-t-transparent" />
              Opening Chrome and joining {url || "the meeting"}…
            </motion.div>
          )}

          {stage === "recording" && (
            <motion.div
              key="recording"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex flex-col items-center gap-4 py-2"
            >
              <div className="flex items-center gap-2 text-sm text-muted">
                <span className="h-2 w-2 animate-pulse rounded-full bg-red-500" />
                Recording · {minutes}:{seconds}
              </div>
              <Waveform />
              <button
                onClick={stop}
                className="rounded-lg border border-border px-5 py-2.5 text-sm font-medium transition hover:bg-background"
              >
                Stop & Transcribe
              </button>
            </motion.div>
          )}

          {stage === "transcribing" && (
            <motion.div
              key="transcribing"
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="flex items-center gap-3 py-4 text-sm text-muted"
            >
              <span className="h-4 w-4 animate-spin rounded-full border-2 border-accent-b border-t-transparent" />
              Running Whisper over the recording…
            </motion.div>
          )}

          {stage === "done" && (
            <motion.div
              key="done"
              initial={{ opacity: 0, y: 8 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0 }}
              className="flex flex-col gap-4"
            >
              <pre className="max-h-56 overflow-y-auto whitespace-pre-wrap rounded-lg border border-border bg-background p-4 text-xs leading-relaxed text-muted">
                {SAMPLE_TRANSCRIPT}
              </pre>
              <div className="flex flex-wrap gap-3">
                <button
                  onClick={download}
                  className="rounded-lg bg-foreground px-4 py-2.5 text-sm font-medium text-background transition hover:opacity-90"
                >
                  Download Sample Transcript
                </button>
                <button
                  onClick={reset}
                  className="rounded-lg border border-border px-4 py-2.5 text-sm font-medium transition hover:bg-background"
                >
                  Run Again
                </button>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </motion.div>
    </section>
  );
}
